name: API Deploy to Heroku

on:
  push:
    branches:
      - api

jobs:
  test:
    name: Unit Test
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: cd api && npm install
      - name: Run tests
        run: cd api && npm test
      - name: Test Report
        uses: dorny/test-reporter@v1
        if: success() || failure()
        with:
          name: JEST Tests
          path: reports/jest-*.xml
          reporter: jest-junit
  deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build, Push and Release a Docker container to Heroku
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: c6888078-bf9e-4ef1-9ffc-c69e5e4d7053
          heroku_app_name: "service-perf-analytics"
          heroku_email: "kilincaslanmesut@gmail.com"
          appdir: "api"
          usedocker: true